---
# This file contains the configuration for the application.  It will probably need to be pregenerated, and contain some commented blocks that will exemplify the usage cases.
# NODES
# - computer_name: 
#   - system: 
#     - Sys_type (Windows/Linux)
#   - archive_root: #The directory which will be shared among all nodes, and will allow for passing of files between the nodes
#     - Directory address, of the type specific to the system type
:admin_email: "ryanmt@byu.net"
:nodes: 
  :instrument: 
    :system: Windows
    :archive_root: O:\
  :metrics: 
    :system: Windows
    :archive_root: O:\
    :program_locale: C:\\NISTMSQCv1_2_0\\scripts\\run_NISTMSQC_pipeline.pl
  :server: 
    :system: Linux
    :archive_root: /media/orbitrap
# QC Control
:quality_control: 
- :name: Trypsin BSA digest
  :filter: QC_bsa
- :name: HEK_digest
  :filter: QC_hek
